services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  thanos-sidecar:
    image: thanosio/thanos:v0.30.2
    command:
      - sidecar
      - --prometheus.url=http://prometheus:9090
      - --tsdb.path=/prometheus
      - --objstore.config-file=/etc/thanos/bucket.yml
    volumes:
      - ./prometheus:/prometheus
      - ./bucket.yml:/etc/thanos/bucket.yml
    environment:
      - S3_BUCKET=${S3_BUCKET}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
    ports:
      - "10901:10901"
    depends_on:
      - prometheus
    env_file:
      - .env

  example-service:
    build: .
    ports:
      - "8000:80"