global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus-monitor'
    replica: 'prometheus-1'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'example-service'
    static_configs:
      - targets: ['example-service:8000']
